
### sign-up - Cadastro
POST http://localhost:3333/sign-up
Content-type: application/json

{
    "email": "jonasfranco@grupocpa.com.br",
    "password": "123456"
}

### sign-in - login
POST http://localhost:3333/sign-in
Content-type: application/json

{
    "email": "jonasfranco@grupocpa.com.br",
    "password": "123456"
}

### Profile
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjE0ZWYyOC0yZjMyLTQ5NjItOTNjZi0wNGE4MzAwMWIzNDEiLCJpYXQiOjE3ODMzNDA1NTYsImV4cCI6MTc4MzQyNjk1Nn0.he-DXHnZ8N1N4e99iuieInPb3pV6nIuDJgLq_of5HUc
GET http://localhost:3333/profile
Content-type: application/json
Authorization: Bearer {{token}}
