
### sign-up - Cadastro
POST http://localhost:3333/sign-up
Content-type: application/json

{
    "email": "jonasfranco@grupocpa.com.br",
    "password": "123456"
}

### sign-in - login
POST http://localhost:3333/sign-in
Content-type: application/json

{
    "email": "jonasfranco@grupocpa.com.br",
    "password": "123456"
}

### Profile
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYmM5NjVmMS1mMDMxLTQwOTUtYWVlMy0yYTQxNjUzOWVhZDYiLCJpYXQiOjE3ODMzODQxMzcsImV4cCI6MTc4MzQ3MDUzN30.Q_85Rfrpz-iA2vPTxj9gZ30HfCEl89akKUL6KvgnS9o
GET http://localhost:3333/profile
Content-type: application/json
Authorization: Bearer {{token}}
